# Generated by Django 4.1.3 on 2023-02-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
