# Generated by Django 4.1.3 on 2023-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visia', '0002_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('EmailID', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=200)),
                ('Qualification', models.TextField(max_length=200)),
                ('Experience', models.TextField(max_length=200)),
            ],
        ),
    ]
