# Generated by Django 4.1.3 on 2023-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visia', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Name',
            field=models.CharField(max_length=250),
        ),
    ]
