# Generated by Django 4.1.3 on 2023-03-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('location', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('Image', models.ImageField(default='', upload_to='pics')),
                ('salary', models.IntegerField(default=0)),
                ('age', models.CharField(default='', max_length=200)),
                ('hiredate', models.DateField(default='2023-02-27')),
                ('price', models.IntegerField(default='333')),
                ('dept', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='calc.department')),
            ],
        ),
    ]
